version: '3.8'
services:
  client:
    build: ./client
    container_name: client-react
    env_file:
      - .env
    depends_on:
      - server
    networks:
      - postgres_network
    restart: on-failure
    stdin_open: true
    ports:
      - "3000:3000"
  server:
    build: ./server
    container_name: server-express
    restart: on-failure
    networks:
      - postgres_network
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "3080:3080"
  postgres:
    image: postgres:13.0-alpine
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      NODE_OPTIONS: "--max-old-space-size=4096"
    volumes:
      -   postgres_container:/var/lib/postgresql/data/
    networks:
      - postgres_network
    ports:
      - "5432:5432"
volumes:
  postgres_container:
networks:
  postgres_network:
    driver: bridge